name: Deploy on merge into main
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy_production:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Deploy'
