name: Deploy on merge into main
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_and_deploy_production:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Deploy'
